# Generated by Django 2.2.5 on 2019-09-06 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190905_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='categroy',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='date',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
