# Generated by Django 2.2.5 on 2019-09-07 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20190907_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='extra',
            field=models.DateField(default='2012-02-02'),
            preserve_default=False,
        ),
    ]
