# Generated by Django 2.2.5 on 2019-09-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_job_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='extra',
            field=models.DateField(verbose_name='2019-02-02'),
        ),
    ]
