# Generated by Django 2.2.5 on 2019-09-07 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20190907_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='extra',
        ),
    ]
